### ISSUE TITLE
Fix broken images

### ISSUE THREAD

**Issue by tacosontitan** [tacosontitan/interactive-pokemon-puzzle#1]
There are several sprites that have broken images, they should be repaired, even if they need to be manually added images.

**Comment by chetanbuddh95** [comment]
Hi @tacosontitan,
Created a [PR](https://github.com/tacosontitan/interactive-pokemon-puzzle/pull/2) to resolve the issue.
Please review it.

**Comment by tacosontitan** [comment]
@chetanbuddh95 I've reviewed, approved, and merged your PR, thanks for the help!
